// Generated by scripts/sync-shared.mjs from shared/client/settings/settings-form.ts. Do not edit this copy; edit the shared source and run "node scripts/sync-shared.mjs".
/**
 * Staged form model behind the plugin settings card. A card stages what the
 * user types and writes it only when they save — the settings write is a
 * durable, revision-fenced document mutation, so staging keeps what is on
 * screen exactly what a save would store. Family-shared slice inlined into
 * each plugin's client bundle; mirrors the official ui-plugin-config
 * card-store pattern.
 */
import { createSnapshotStore } from '@deepseek-ai/dsh-client-store';
/** A whole- or decimal-number field. An empty draft clears the field; any other draft that is not a finite number within the constraints blocks the save. */
export function numberField(field, constraints = {}) {
    const { integer = false, min } = constraints;
    return {
        field,
        format: value => typeof value === 'number' ? String(value) : '',
        parse: (text) => {
            const trimmed = text.trim();
            if (trimmed === '')
                return { kind: 'clear' };
            const parsed = Number(trimmed);
            if (!Number.isFinite(parsed))
                return undefined;
            if (integer && !Number.isInteger(parsed))
                return undefined;
            if (min !== undefined && parsed < min)
                return undefined;
            return { kind: 'set', value: parsed };
        },
    };
}
/** A free-text field. An empty draft clears the field. */
export function textField(field) {
    return {
        field,
        format: value => typeof value === 'string' ? value : '',
        parse: (text) => {
            const trimmed = text.trim();
            return trimmed === '' ? { kind: 'clear' } : { kind: 'set', value: trimmed };
        },
    };
}
/**
 * A free-text field the Host treats as a secret and redacts from the read-back
 * (role('secret') in the section schema). The card still edits it like text,
 * but a save never compares the redacted value back: the staged set is judged
 * by the mutation settling (see {@link FieldSpec.secret}).
 */
export function secretField(field) {
    return { ...textField(field), secret: true };
}
/** A boolean field, edited through true/false draft text. */
export function booleanField(field) {
    return {
        field,
        format: value => typeof value === 'boolean' ? String(value) : '',
        parse: (text) => {
            const trimmed = text.trim();
            if (trimmed === '')
                return { kind: 'clear' };
            if (trimmed === 'true')
                return { kind: 'set', value: true };
            if (trimmed === 'false')
                return { kind: 'set', value: false };
            return undefined;
        },
    };
}
/** An enumerated string field; only the listed choices are accepted. An empty draft clears the field. */
export function choiceField(field, choices) {
    return {
        field,
        format: value => typeof value === 'string' && choices.includes(value) ? value : '',
        parse: (text) => {
            if (text === '')
                return { kind: 'clear' };
            return choices.includes(text) ? { kind: 'set', value: text } : undefined;
        },
    };
}
/**
 * Stages one card's edits over one settings namespace and writes them on save.
 *
 * The Host is the only authority on whether a value was accepted — its
 * validators own the constraints no schema can express — so the outcome is
 * read back from the section rather than predicted here. A save that did not
 * land keeps its drafts, so the user can correct them instead of retyping.
 */
export class CardForm {
    scope;
    specs;
    staged = new Map();
    listeners = new Set();
    /** The form subscription installed in the constructor; released by dispose(). */
    disposeForm;
    disposed = false;
    saving = false;
    failed = false;
    failedReason;
    /** @param scope - the bound configuration form for this card's namespace. */
    constructor(scope, specs) {
        this.scope = scope;
        this.specs = new Map(specs.map(spec => [spec.field, spec]));
        this.disposeForm = scope.subscribe(() => { this.publish(); });
    }
    /**
     * Release the form subscription and every bound store listener. The card
     * must call this on teardown; later calls are no-ops.
     */
    dispose() {
        if (this.disposed)
            return;
        this.disposed = true;
        this.disposeForm();
        this.listeners.clear();
    }
    /** Publish a projection of this form, rebuilt whenever the form or a draft changes. */
    bind(project) {
        const store = createSnapshotStore(project());
        this.listeners.add(() => { store.set(project()); });
        return store;
    }
    /** Read the card-level state: what the Host serves, and what a save would do. */
    shell() {
        const snapshot = this.scope.getSnapshot();
        const plan = this.plan();
        return {
            available: snapshot.status !== 'loading',
            exposed: snapshot.status === 'ready',
            writable: snapshot.writable,
            dirty: plan.length > 0,
            invalid: plan.some(item => item.judge === undefined),
            saving: this.saving,
            failed: this.failed,
            ...this.failedReason === undefined ? {} : { failedReason: this.failedReason },
        };
    }
    /** Read one field's state from the effective section and its staged draft. */
    field(field) {
        const spec = this.specOf(field);
        const staged = this.staged.get(field);
        if (staged === undefined) {
            return { text: spec.format(this.sectionValue(field)), overridden: this.stored(field), invalid: false };
        }
        const write = staged.clear ? { kind: 'clear' } : spec.parse(staged.text);
        return {
            text: staged.text,
            overridden: write?.kind === 'set',
            invalid: write === undefined,
        };
    }
    /** The actions the card's slot registration injects. */
    actions() {
        return {
            edit: (field, text) => { this.stage(field, { text, clear: false }); },
            resetField: (field) => {
                this.stage(field, { text: this.specOf(field).format(this.baseValue(field)), clear: true });
            },
            save: () => { void this.save(); },
            discard: () => {
                if (this.staged.size === 0 && !this.failed)
                    return;
                this.staged.clear();
                this.failed = false;
                this.failedReason = undefined;
                this.publish();
            },
        };
    }
    /**
     * Write every staged edit in one atomic form mutation, then re-seed from
     * what the Host accepted.
     *
     * The whole batch rides one mutate, so cross-field validate hooks
     * (baseURL+model) judge it as a unit: the Host either applies every write
     * or refuses the batch. The form contract answers a refusal or a skipped
     * write with `false` (it recovers with a fresh Host view instead of
     * throwing), so the outcome is judged twice: the answer itself, and then the
     * settled snapshot read back one planned write at a time. One missed write
     * fails the whole save. A transport that rejects instead (the dsh-web bridge
     * controller on a dead connection) reports through the same failure path
     * with its rejection message. A save that did not land keeps its drafts, so
     * the user can correct them instead of retyping.
     * @returns settlement after the mutation and the read-back.
     */
    async save() {
        const plan = this.plan();
        const valid = plan.filter((item) => item.judge !== undefined);
        if (plan.length === 0 || this.saving || valid.length !== plan.length)
            return;
        // Snapshot the staged entries this save writes, so an edit staged while it
        // is in flight (which replaces the same key) survives: only delete the key
        // when the entry is still the one this save started from.
        const pending = new Map();
        for (const item of plan)
            pending.set(item.field, this.staged.get(item.field));
        this.saving = true;
        this.failed = false;
        this.failedReason = undefined;
        this.publish();
        // One atomic namespace mutation: the form contract takes ordered path
        // operations, so the whole staged batch is validated, persisted, and
        // recovered together — either every write lands or none does.
        const ops = valid.map(item => item.op.op === 'set'
            ? { op: 'set', path: [item.field], value: item.op.value }
            : { op: 'unset', path: [item.field] });
        let failedReason;
        let accepted = false;
        try {
            accepted = await this.scope.mutate(ops);
        }
        catch (error) {
            failedReason = error instanceof Error ? error.message : String(error);
        }
        // `false` is the contract's refusal/skip answer, and the form still
        // resolves after a refusal (it recovers with a fresh view), so the answer
        // alone is not enough: judge every planned write against the settled
        // snapshot as well. The mutation is atomic, so one missed write fails the
        // whole save and keeps the drafts.
        const landed = accepted && failedReason === undefined && valid.every(item => item.judge());
        for (const [field, before] of pending) {
            if (landed && this.staged.get(field) === before)
                this.staged.delete(field);
        }
        this.saving = false;
        this.failed = !landed;
        // A refused or unlanded batch carries no server reason: the card surfaces
        // its generic failure copy; a rejecting transport (the bridge) adds its
        // message.
        this.failedReason = failedReason;
        this.publish();
    }
    /**
     * Every staged edit a save would write. An entry whose draft is not a value
     * its field accepts carries no write: the form is still dirty, and the save
     * refuses rather than dropping the edit. A staged edit that matches the
     * effective section is not a write at all.
     * @returns the planned writes, in the order the fields were staged.
     */
    plan() {
        const plan = [];
        for (const [field, staged] of this.staged) {
            const spec = this.specOf(field);
            if (staged.clear) {
                if (this.stored(field))
                    plan.push({ field, op: { field, op: 'unset' }, judge: () => this.landedUnset(field) });
                continue;
            }
            if (staged.text === spec.format(this.sectionValue(field)))
                continue;
            const write = spec.parse(staged.text);
            if (write === undefined)
                plan.push({ field, op: { field, op: 'unset' }, judge: undefined });
            else if (write.kind === 'clear')
                plan.push({ field, op: { field, op: 'unset' }, judge: () => this.landedUnset(field) });
            else
                plan.push({ field, op: { field, op: 'set', value: write.value }, judge: () => this.landedSet(field, write.value) });
        }
        return plan;
    }
    /**
     * Read-back judgment for a planned set: the user layer must hold the
     * intended value once the mutation has settled.
     */
    landedSet(field, value) {
        // A redacted secret never appears in any wire view layer: the Host strips
        // role('secret') fields and reports them through a sidecar the form
        // snapshot does not expose, so there is nothing to compare the draft
        // against. Settling is the only signal the form has; the rest of the
        // batch, when one exists, still carries the atomic verdict by read-back.
        if (this.specOf(field).secret)
            return true;
        return this.userLayer()?.[field] === value;
    }
    /**
     * Read-back judgment for a planned unset: the field must be gone from the
     * user layer once the mutation has settled.
     */
    landedUnset(field) {
        return !this.stored(field);
    }
    stage(field, edit) {
        this.staged.set(field, edit);
        this.failed = false;
        this.failedReason = undefined;
        this.publish();
    }
    specOf(field) {
        const spec = this.specs.get(field);
        // Every call site names a field this card declared; a missing one is a
        // wiring mistake that must not degrade into a silently inert control.
        if (spec === undefined)
            throw new Error(`settings card has no field ${field}`);
        return spec;
    }
    snapshotOf() {
        return this.scope.getSnapshot();
    }
    sectionValue(field) {
        return this.snapshotOf().value?.[field];
    }
    baseValue(field) {
        return this.snapshotOf().base?.[field];
    }
    userLayer() {
        return this.snapshotOf().user;
    }
    stored(field) {
        const user = this.userLayer();
        return user !== undefined && Object.hasOwn(user, field);
    }
    publish() {
        for (const listener of this.listeners)
            listener();
    }
}
